### ISSUE TITLE
`NOSUGGEST` support

### ISSUE THREAD

**Issue by whawker** [darmeth/british-english-language-tools#1]
Hi @darmeth 

Would you consider a PR that adds a `NOSUGGEST` rule to the `aff` file to prevent the suggestion of vulgar words?

**Comment by darmeth** [comment]
Hi @whawker 

Yes, definitely. Please send through a pull we can get this added.

**Comment by whawker** [comment]
Added #2

**Comment by darmeth** [comment]
Pull merged. Many thanks
